# Generated by Django 5.1.2 on 2026-02-03 08:32

import bookapp.validators
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('image', models.ImageField(upload_to='rewards/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Шаблон приза',
                'verbose_name_plural': 'Шаблоны призов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_img')),
                ('profile_picture_url', models.URLField(blank=True, null=True)),
                ('job_title', models.CharField(blank=True, max_length=50, null=True)),
                ('facebook', models.URLField(blank=True, max_length=255, null=True)),
                ('youtube', models.URLField(blank=True, max_length=255, null=True)),
                ('instagram', models.URLField(blank=True, max_length=255, null=True)),
                ('twitter', models.URLField(blank=True, max_length=255, null=True)),
                ('linkedin', models.URLField(blank=True, max_length=255, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('content_type', models.CharField(choices=[('plaintext', 'Plain Text'), ('epub', 'EPUB')], default='plaintext', max_length=20)),
                ('epub_file', models.FileField(blank=True, null=True, upload_to='epub_files/', validators=[bookapp.validators.validate_epub_file_extension, bookapp.validators.validate_epub_file_size, bookapp.validators.validate_file_is_not_empty])),
                ('table_of_contents', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('is_draft', models.BooleanField(default=True)),
                ('category', models.CharField(blank=True, choices=[('Science Fiction', 'Science Fiction'), ('Fantasy', 'Fantasy'), ('Detective Fiction', 'Detective Fiction'), ('Thriller', 'Thriller'), ('Romance', 'Romance'), ('Horror', 'Horror'), ('Historical Fiction', 'Historical Fiction'), ('Adventure', 'Adventure')], max_length=255, null=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='book_img')),
                ('visibility', models.CharField(choices=[('public', 'Публичная (видимая всем)'), ('group', 'Групповая (видимая только членам вашей группы)'), ('personal', 'Личная (видимая только вам)')], default='public', max_length=20)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='BookReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('stars_amount', models.IntegerField(verbose_name='Звезды')),
                ('creation_date', models.DateField(verbose_name='Дата создания')),
                ('likes', models.JSONField(verbose_name='Лайки')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookapp.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Отзыв к книге',
                'verbose_name_plural': 'Отзывы к книге',
            },
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('quest_type', models.CharField(choices=[('read_books', 'Прочитать книги'), ('create_comments', 'Оставить комментарии'), ('reply_comments', 'Ответить на комментарии'), ('place_rewards', 'Разместить призы')], max_length=50, verbose_name='Тип задания')),
                ('target_count', models.PositiveIntegerField(help_text='Сколько нужно выполнить действий', verbose_name='Целевое количество')),
                ('period', models.CharField(choices=[('day', 'День'), ('week', 'Неделя'), ('month', 'Месяц')], max_length=20, verbose_name='Период')),
                ('participation_type', models.CharField(choices=[('personal', 'Персональное'), ('group', 'Групповое')], max_length=20, verbose_name='Тип участия')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('is_completed', models.BooleanField(default=False, help_text='Задание выполнено и награды розданы', verbose_name='Завершено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_quests', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReadingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='reading_group_img')),
                ('description', models.TextField(blank=True, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reading_groups_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата завершения')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='bookapp.quest', verbose_name='Задание')),
                ('user', models.ForeignKey(help_text='Для персональных заданий', on_delete=django.db.models.deletion.CASCADE, related_name='completed_quests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('reading_group', models.ForeignKey(blank=True, help_text='Для групповых заданий', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completed_quests', to='bookapp.readinggroup', verbose_name='Группа чтения')),
            ],
            options={
                'verbose_name': 'Завершённое задание',
                'verbose_name_plural': 'Завершённые задания',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.AddField(
            model_name='quest',
            name='reading_group',
            field=models.ForeignKey(blank=True, help_text='Если null - глобальное задание', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quests', to='bookapp.readinggroup', verbose_name='Группа чтения'),
        ),
        migrations.CreateModel(
            name='PrizeBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.PositiveIntegerField(default=5, help_text='Количество колонок', verbose_name='Ширина')),
                ('height', models.PositiveIntegerField(default=5, help_text='Количество строк', verbose_name='Высота')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('reading_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prize_board', to='bookapp.readinggroup', verbose_name='Группа чтения')),
            ],
            options={
                'verbose_name': 'Поле для призов',
                'verbose_name_plural': 'Поля для призов',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='reading_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='bookapp.readinggroup'),
        ),
        migrations.AddField(
            model_name='quest',
            name='reward_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quests', to='bookapp.rewardtemplate', verbose_name='Приз'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_text', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(blank=True, choices=[('GroupJoinRequest', 'GroupJoinRequest'), ('GroupRequestDeclined', 'GroupRequestDeclined'), ('GroupRequestAccepted', 'GroupRequestAccepted'), ('QuestCompleted', 'QuestCompleted')], max_length=255, null=True)),
                ('directed_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directed_to', to=settings.AUTH_USER_MODEL)),
                ('related_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_to', to=settings.AUTH_USER_MODEL)),
                ('related_quest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='bookapp.quest', verbose_name='Связанное задание')),
                ('related_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_group', to='bookapp.readinggroup')),
                ('related_reward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='bookapp.rewardtemplate', verbose_name='Связанная награда')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='UserReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата получения')),
                ('quest_completed', models.ForeignKey(blank=True, help_text='За какое задание получен приз', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rewards_given', to='bookapp.questcompletion', verbose_name='Задание')),
                ('reward_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rewards', to='bookapp.rewardtemplate', verbose_name='Шаблон приза')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Полученный приз',
                'verbose_name_plural': 'Полученные призы',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quests_completed', models.PositiveIntegerField(default=0, verbose_name='Всего заданий выполнено')),
                ('total_books_read', models.PositiveIntegerField(default=0, verbose_name='Всего книг прочитано')),
                ('total_comments_created', models.PositiveIntegerField(default=0, verbose_name='Всего комментариев создано')),
                ('total_replies_created', models.PositiveIntegerField(default=0, verbose_name='Всего ответов создано')),
                ('total_rewards_received', models.PositiveIntegerField(default=0, verbose_name='Всего призов получено')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Статистика пользователя',
                'verbose_name_plural': 'Статистика пользователей',
            },
        ),
        migrations.CreateModel(
            name='UserToReadingGroupState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_reading_group', models.BooleanField(default=False)),
                ('reading_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookapp.readinggroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['in_reading_group'],
            },
        ),
        migrations.AddField(
            model_name='readinggroup',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='reading_groups_user', through='bookapp.UserToReadingGroupState', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='QuestProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_count', models.PositiveIntegerField(default=0, verbose_name='Текущий прогресс')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='bookapp.quest', verbose_name='Задание')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_progress', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Прогресс задания',
                'verbose_name_plural': 'Прогресс заданий',
                'indexes': [models.Index(fields=['quest', 'user'], name='bookapp_que_quest_i_db8f94_idx')],
                'unique_together': {('quest', 'user')},
            },
        ),
        migrations.CreateModel(
            name='BookComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cfi_range', models.TextField(blank=True, help_text='EPUB CFI range identifying the exact text location (null for replies)', null=True)),
                ('selected_text', models.TextField(blank=True, help_text='The actual text that was selected and commented on (null for replies)', null=True)),
                ('comment_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('highlight_color', models.CharField(default='#FFFF00', help_text='Hex color code for highlighting the commented text', max_length=7)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='bookapp.book')),
                ('parent_comment', models.ForeignKey(blank=True, help_text='Parent comment if this is a reply (null for root comments)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='bookapp.bookcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_comments', to=settings.AUTH_USER_MODEL)),
                ('reading_group', models.ForeignKey(blank=True, help_text='Reading group this comment belongs to (null for personal comments)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_comments', to='bookapp.readinggroup')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['book', 'reading_group'], name='bookapp_boo_book_id_2e0b6a_idx'), models.Index(fields=['user', 'reading_group'], name='bookapp_boo_user_id_3597d1_idx'), models.Index(fields=['book', 'user'], name='bookapp_boo_book_id_0ffb5b_idx'), models.Index(fields=['parent_comment'], name='bookapp_boo_parent__355a31_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReadingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_cfi', models.CharField(blank=True, help_text='EPUB CFI - текущая позиция в книге', max_length=500, verbose_name='Текущая позиция')),
                ('current_page', models.IntegerField(default=1, help_text='Номер текущей страницы для обычных книг', verbose_name='Текущая страница')),
                ('total_pages', models.IntegerField(default=1, help_text='Общее количество страниц', verbose_name='Всего страниц')),
                ('progress_percent', models.FloatField(default=0, help_text='Процент прочитанного (0-100)', verbose_name='Прогресс (%)')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершено')),
                ('last_read_at', models.DateTimeField(auto_now=True, verbose_name='Последнее чтение')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to='bookapp.book', verbose_name='Книга')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Прогресс чтения',
                'verbose_name_plural': 'Прогресс чтения',
                'indexes': [models.Index(fields=['user', 'book'], name='bookapp_rea_user_id_cd0465_idx'), models.Index(fields=['user', 'is_completed'], name='bookapp_rea_user_id_03f4ac_idx')],
                'unique_together': {('user', 'book')},
            },
        ),
        migrations.CreateModel(
            name='PrizeBoardCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveIntegerField(verbose_name='Координата X')),
                ('y', models.PositiveIntegerField(verbose_name='Координата Y')),
                ('placed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата размещения')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='bookapp.prizeboard', verbose_name='Поле')),
                ('placed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placed_rewards', to=settings.AUTH_USER_MODEL, verbose_name='Размещено пользователем')),
                ('user_reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_placements', to='bookapp.userreward', verbose_name='Приз пользователя')),
            ],
            options={
                'verbose_name': 'Ячейка поля призов',
                'verbose_name_plural': 'Ячейки поля призов',
                'indexes': [models.Index(fields=['board', 'x', 'y'], name='bookapp_pri_board_i_6dc6f2_idx')],
                'unique_together': {('board', 'x', 'y')},
            },
        ),
        migrations.CreateModel(
            name='UserRewardSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_count', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('last_received_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя дата получения')),
                ('reward_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_summaries', to='bookapp.rewardtemplate', verbose_name='Шаблон приза')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_summaries', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сводка по призам',
                'verbose_name_plural': 'Сводки по призам',
                'indexes': [models.Index(fields=['user', 'reward_template'], name='bookapp_use_user_id_657e96_idx')],
                'unique_together': {('user', 'reward_template')},
            },
        ),
    ]
