# Generated by Django 5.1.2 on 2026-02-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingprogress',
            name='character_offset',
            field=models.IntegerField(default=0, help_text='Индекс первого символа на текущей странице (для TXT)', verbose_name='Позиция символа'),
        ),
    ]
