# Generated by Django 6.0.1 on 2026-01-31 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(blank=True, choices=[('GroupJoinRequest', 'GroupJoinRequest'), ('GroupRequestDeclined', 'GroupRequestDeclined'), ('GroupRequestAccepted', 'GroupRequestAccepted'), ('QuestCompleted', 'QuestCompleted')], max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='BookReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('stars_amount', models.IntegerField(verbose_name='Звезды')),
                ('creation_date', models.DateField(verbose_name='Дата создания')),
                ('likes', models.JSONField(verbose_name='Лайки')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookapp.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Отзыв к книге',
                'verbose_name_plural': 'Отзывы к книге',
            },
        ),
        migrations.CreateModel(
            name='PrizeBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.PositiveIntegerField(default=5, help_text='Количество колонок', verbose_name='Ширина')),
                ('height', models.PositiveIntegerField(default=5, help_text='Количество строк', verbose_name='Высота')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('reading_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prize_board', to='bookapp.readinggroup', verbose_name='Группа чтения')),
            ],
            options={
                'verbose_name': 'Поле для призов',
                'verbose_name_plural': 'Поля для призов',
            },
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('quest_type', models.CharField(choices=[('read_books', 'Прочитать книги'), ('create_comments', 'Оставить комментарии'), ('reply_comments', 'Ответить на комментарии'), ('place_rewards', 'Разместить призы')], max_length=50, verbose_name='Тип задания')),
                ('target_count', models.PositiveIntegerField(help_text='Сколько нужно выполнить действий', verbose_name='Целевое количество')),
                ('period', models.CharField(choices=[('day', 'День'), ('week', 'Неделя'), ('month', 'Месяц')], max_length=20, verbose_name='Период')),
                ('participation_type', models.CharField(choices=[('personal', 'Персональное'), ('group', 'Групповое')], max_length=20, verbose_name='Тип участия')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_quests', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('reading_group', models.ForeignKey(blank=True, help_text='Если null - глобальное задание', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quests', to='bookapp.readinggroup', verbose_name='Группа чтения')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата завершения')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='bookapp.quest', verbose_name='Задание')),
                ('reading_group', models.ForeignKey(blank=True, help_text='Для групповых заданий', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completed_quests', to='bookapp.readinggroup', verbose_name='Группа чтения')),
                ('user', models.ForeignKey(help_text='Для персональных заданий', on_delete=django.db.models.deletion.CASCADE, related_name='completed_quests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Завершённое задание',
                'verbose_name_plural': 'Завершённые задания',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='RewardTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('image', models.ImageField(upload_to='rewards/', verbose_name='Изображение')),
                ('properties', models.JSONField(blank=True, default=dict, help_text='Дополнительные свойства приза (JSON)', verbose_name='Свойства')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_rewards', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('reading_group', models.ForeignKey(blank=True, help_text='Если null - глобальный приз', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='bookapp.readinggroup', verbose_name='Группа чтения')),
            ],
            options={
                'verbose_name': 'Шаблон приза',
                'verbose_name_plural': 'Шаблоны призов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='quest',
            name='reward_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quests', to='bookapp.rewardtemplate', verbose_name='Приз'),
        ),
        migrations.CreateModel(
            name='UserReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата получения')),
                ('quest_completed', models.ForeignKey(blank=True, help_text='За какое задание получен приз', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rewards_given', to='bookapp.questcompletion', verbose_name='Задание')),
                ('reward_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rewards', to='bookapp.rewardtemplate', verbose_name='Шаблон приза')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Полученный приз',
                'verbose_name_plural': 'Полученные призы',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quests_completed', models.PositiveIntegerField(default=0, verbose_name='Всего заданий выполнено')),
                ('total_books_read', models.PositiveIntegerField(default=0, verbose_name='Всего книг прочитано')),
                ('total_comments_created', models.PositiveIntegerField(default=0, verbose_name='Всего комментариев создано')),
                ('total_rewards_received', models.PositiveIntegerField(default=0, verbose_name='Всего призов получено')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Статистика пользователя',
                'verbose_name_plural': 'Статистика пользователей',
            },
        ),
        migrations.CreateModel(
            name='QuestProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_count', models.PositiveIntegerField(default=0, verbose_name='Текущий прогресс')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='bookapp.quest', verbose_name='Задание')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_progress', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Прогресс задания',
                'verbose_name_plural': 'Прогресс заданий',
                'indexes': [models.Index(fields=['quest', 'user'], name='bookapp_que_quest_i_db8f94_idx')],
                'unique_together': {('quest', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ReadingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_cfi', models.CharField(blank=True, help_text='EPUB CFI - текущая позиция в книге', max_length=500, verbose_name='Текущая позиция')),
                ('progress_percent', models.FloatField(default=0, help_text='Процент прочитанного (0-100)', verbose_name='Прогресс (%)')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершено')),
                ('last_read_at', models.DateTimeField(auto_now=True, verbose_name='Последнее чтение')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to='bookapp.book', verbose_name='Книга')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Прогресс чтения',
                'verbose_name_plural': 'Прогресс чтения',
                'indexes': [models.Index(fields=['user', 'book'], name='bookapp_rea_user_id_cd0465_idx'), models.Index(fields=['user', 'is_completed'], name='bookapp_rea_user_id_03f4ac_idx')],
                'unique_together': {('user', 'book')},
            },
        ),
        migrations.CreateModel(
            name='PrizeBoardCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveIntegerField(verbose_name='Координата X')),
                ('y', models.PositiveIntegerField(verbose_name='Координата Y')),
                ('placed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата размещения')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='bookapp.prizeboard', verbose_name='Поле')),
                ('placed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placed_rewards', to=settings.AUTH_USER_MODEL, verbose_name='Размещено пользователем')),
                ('user_reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_placements', to='bookapp.userreward', verbose_name='Приз пользователя')),
            ],
            options={
                'verbose_name': 'Ячейка поля призов',
                'verbose_name_plural': 'Ячейки поля призов',
                'indexes': [models.Index(fields=['board', 'x', 'y'], name='bookapp_pri_board_i_6dc6f2_idx')],
                'unique_together': {('board', 'x', 'y')},
            },
        ),
    ]
