# Generated by Django 5.1.2 on 2026-02-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Хештег',
                'verbose_name_plural': 'Хештеги',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='hashtags',
            field=models.ManyToManyField(blank=True, related_name='books', to='bookapp.hashtag'),
        ),
    ]
