# Generated by Django 5.1.2 on 2026-02-05 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='youtube',
        ),
    ]
