# Generated by Django 5.1.2 on 2026-01-27 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cfi_range', models.TextField(help_text='EPUB CFI range identifying the exact text location')),
                ('selected_text', models.TextField(help_text='The actual text that was selected and commented on')),
                ('comment_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('highlight_color', models.CharField(default='#FFFF00', help_text='Hex color code for highlighting the commented text', max_length=7)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='bookapp.book')),
                ('reading_group', models.ForeignKey(help_text='Reading group this comment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='book_comments', to='bookapp.readinggroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['book', 'reading_group'], name='bookapp_boo_book_id_2e0b6a_idx'), models.Index(fields=['user', 'reading_group'], name='bookapp_boo_user_id_3597d1_idx')],
            },
        ),
    ]
