# Generated by Django 5.1.2 on 2026-01-28 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_bookcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcomment',
            name='reading_group',
            field=models.ForeignKey(blank=True, help_text='Reading group this comment belongs to (null for personal comments)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_comments', to='bookapp.readinggroup'),
        ),
        migrations.AddIndex(
            model_name='bookcomment',
            index=models.Index(fields=['book', 'user'], name='bookapp_boo_book_id_0ffb5b_idx'),
        ),
    ]
