# Generated by Django 5.1.2 on 2026-02-04 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_add_character_offset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readingprogress',
            name='current_page',
        ),
        migrations.RemoveField(
            model_name='readingprogress',
            name='total_pages',
        ),
    ]
