# Generated by Django 5.1.2 on 2026-02-05 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_remove_customuser_facebook_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readingprogress',
            name='character_offset',
        ),
        migrations.AddField(
            model_name='prizeboard',
            name='board_type',
            field=models.CharField(choices=[('group', 'Группа'), ('user', 'Пользователь')], default='group', max_length=10, verbose_name='Тип доски'),
        ),
        migrations.AddField(
            model_name='prizeboard',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prize_board', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='readingprogress',
            name='current_page',
            field=models.IntegerField(default=1, help_text='Номер текущей страницы для обычных книг', verbose_name='Текущая страница'),
        ),
        migrations.AddField(
            model_name='readingprogress',
            name='total_pages',
            field=models.IntegerField(default=1, help_text='Общее количество страниц', verbose_name='Всего страниц'),
        ),
        migrations.AlterField(
            model_name='prizeboard',
            name='reading_group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prize_board', to='bookapp.readinggroup', verbose_name='Группа чтения'),
        ),
    ]
