# Generated by Django 5.1.2 on 2026-02-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_hashtag_book_hashtags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readingprogress',
            name='current_page',
        ),
        migrations.RemoveField(
            model_name='readingprogress',
            name='total_pages',
        ),
        migrations.AddField(
            model_name='readingprogress',
            name='character_offset',
            field=models.IntegerField(default=0, help_text='Индекс первого символа на текущей странице (для TXT)', verbose_name='Позиция символа'),
        ),
    ]
