# Generated by Django 5.1.2 on 2026-01-31 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_alter_notification_category_bookreview_prizeboard_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rewardtemplate',
            options={'ordering': ['name'], 'verbose_name': 'Шаблон приза', 'verbose_name_plural': 'Шаблоны призов'},
        ),
        migrations.RemoveField(
            model_name='rewardtemplate',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='rewardtemplate',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='rewardtemplate',
            name='properties',
        ),
        migrations.RemoveField(
            model_name='rewardtemplate',
            name='reading_group',
        ),
    ]
