# Generated by Django 5.1.2 on 2026-01-29 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0003_alter_bookcomment_reading_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcomment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, help_text='Parent comment if this is a reply (null for root comments)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='bookapp.bookcomment'),
        ),
        migrations.AlterField(
            model_name='bookcomment',
            name='cfi_range',
            field=models.TextField(blank=True, help_text='EPUB CFI range identifying the exact text location (null for replies)', null=True),
        ),
        migrations.AlterField(
            model_name='bookcomment',
            name='selected_text',
            field=models.TextField(blank=True, help_text='The actual text that was selected and commented on (null for replies)', null=True),
        ),
        migrations.AddIndex(
            model_name='bookcomment',
            index=models.Index(fields=['parent_comment'], name='bookapp_boo_parent__355a31_idx'),
        ),
    ]
