# Generated by Django 6.0.1 on 2026-01-31 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0003_alter_rewardtemplate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_quest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='bookapp.quest', verbose_name='Связанное задание'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_reward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='bookapp.rewardtemplate', verbose_name='Связанная награда'),
        ),
        migrations.AddField(
            model_name='quest',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Задание выполнено и награды розданы', verbose_name='Завершено'),
        ),
    ]
