# Generated by Django 5.1.2 on 2026-02-05 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0003_remove_readingprogress_current_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_author',
            field=models.CharField(default='Неизвестный автор', max_length=255, verbose_name='Автор книги'),
        ),
    ]
