# Generated by Django 5.1.2 on 2026-02-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0003_remove_readingprogress_character_offset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(blank=True, choices=[('GroupJoinRequest', 'GroupJoinRequest'), ('GroupRequestDeclined', 'GroupRequestDeclined'), ('GroupRequestAccepted', 'GroupRequestAccepted'), ('GroupKick', 'GroupKick'), ('QuestCompleted', 'QuestCompleted')], max_length=255, null=True),
        ),
    ]
