# Generated by Django 6.0.1 on 2026-01-31 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0004_add_quest_completion_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingprogress',
            name='current_page',
            field=models.IntegerField(default=1, help_text='Номер текущей страницы для обычных книг', verbose_name='Текущая страница'),
        ),
        migrations.AddField(
            model_name='readingprogress',
            name='total_pages',
            field=models.IntegerField(default=1, help_text='Общее количество страниц', verbose_name='Всего страниц'),
        ),
    ]
