# Generated by Django 5.1.2 on 2026-02-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0004_book_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_author',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Автор книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(blank=True, choices=[('classic', 'Классика'), ('fantasy', 'Фэнтези'), ('detective_fiction', 'Детектив'), ('thriller', 'Триллер'), ('romance', 'Романтика'), ('horror', 'Ужасы'), ('adventure', 'Приключения'), ('science_fiction', 'Научная фантастика'), ('biography', 'Биография'), ('self_help', 'Саморазвитие'), ('poetry', 'Поэзия'), ('children', 'Детская литература'), ('non_fiction', 'Документальная литература'), ('business', 'Бизнес и экономика'), ('other', 'Другое')], max_length=255, null=True),
        ),
    ]
