# Generated by Django 5.1.2 on 2026-02-01 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0006_user_reward_summary'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userrewardsummary',
            new_name='bookapp_use_user_id_657e96_idx',
            old_name='reward_summary_user_reward_template_idx',
        ),
    ]
