# Generated by Django 5.1.2 on 2026-01-24 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_group', to='bookapp.readinggroup'),
        ),
    ]
