# Generated by Django 5.1.2 on 2026-01-24 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0008_notification_related_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToReadingGroupState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_reading_group', models.BooleanField(default=False)),
                ('reading_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookapp.readinggroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['in_reading_group'],
            },
        ),
    ]
