# Generated by Django 5.1.2 on 2026-01-24 14:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0009_usertoreadinggroupstate_alter_readinggroup_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readinggroup',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='reading_groups_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
