# Generated by Django 5.1.2 on 2026-01-25 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0010_alter_readinggroup_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='sent_date',
        ),
    ]
